include: package:lint/analysis_options.yaml

analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    eol_at_end_of_file: ignore
    omit_local_variable_types: ignore
    overridden_fields: ignore
    prefer_collection_literals: ignore
    unnecessary_await_in_return: ignore
    unnecessary_this: ignore
    use_setters_to_change_properties: ignore
